/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppActivityRouteImport } from './routes/app/activity'
import { Route as AppCreateRouteImport } from './routes/app/create'
import { Route as AppCuratorRouteImport } from './routes/app/curator'
import { Route as AppMeRouteImport } from './routes/app/me'
import { Route as AppTradeRouteImport } from './routes/app/trade'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsVaultAgentRouteImport } from './routes/docs.vault-agent'
import { Route as AppTIdRouteImport } from './routes/app/t.$id'
import { Route as AppPChainIdVaultRouteImport } from './routes/app/p.$chainId.$vault'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCuratorRoute = AppCuratorRouteImport.update({
  id: '/curator',
  path: '/curator',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTradeRoute = AppTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AppRouteRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsVaultAgentRoute = DocsVaultAgentRouteImport.update({
  id: '/vault-agent',
  path: '/vault-agent',
  getParentRoute: () => DocsRoute,
} as any)
const AppTIdRoute = AppTIdRouteImport.update({
  id: '/t/$id',
  path: '/t/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPChainIdVaultRoute = AppPChainIdVaultRouteImport.update({
  id: '/p/$chainId/$vault',
  path: '/p/$chainId/$vault',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/security': typeof SecurityRoute
  '/app/activity': typeof AppActivityRoute
  '/app/create': typeof AppCreateRoute
  '/app/curator': typeof AppCuratorRoute
  '/app/me': typeof AppMeRoute
  '/app/trade': typeof AppTradeRoute
  '/docs/vault-agent': typeof DocsVaultAgentRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/app/t/$id': typeof AppTIdRoute
  '/app/p/$chainId/$vault': typeof AppPChainIdVaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/security': typeof SecurityRoute
  '/app/activity': typeof AppActivityRoute
  '/app/create': typeof AppCreateRoute
  '/app/curator': typeof AppCuratorRoute
  '/app/me': typeof AppMeRoute
  '/app/trade': typeof AppTradeRoute
  '/docs/vault-agent': typeof DocsVaultAgentRoute
  '/app': typeof AppIndexRoute
  '/docs': typeof DocsIndexRoute
  '/app/t/$id': typeof AppTIdRoute
  '/app/p/$chainId/$vault': typeof AppPChainIdVaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/security': typeof SecurityRoute
  '/app/activity': typeof AppActivityRoute
  '/app/create': typeof AppCreateRoute
  '/app/curator': typeof AppCuratorRoute
  '/app/me': typeof AppMeRoute
  '/app/trade': typeof AppTradeRoute
  '/docs/vault-agent': typeof DocsVaultAgentRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/app/t/$id': typeof AppTIdRoute
  '/app/p/$chainId/$vault': typeof AppPChainIdVaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/docs'
    | '/security'
    | '/app/activity'
    | '/app/create'
    | '/app/curator'
    | '/app/me'
    | '/app/trade'
    | '/docs/vault-agent'
    | '/app/'
    | '/docs/'
    | '/app/t/$id'
    | '/app/p/$chainId/$vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/security'
    | '/app/activity'
    | '/app/create'
    | '/app/curator'
    | '/app/me'
    | '/app/trade'
    | '/docs/vault-agent'
    | '/app'
    | '/docs'
    | '/app/t/$id'
    | '/app/p/$chainId/$vault'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/docs'
    | '/security'
    | '/app/activity'
    | '/app/create'
    | '/app/curator'
    | '/app/me'
    | '/app/trade'
    | '/docs/vault-agent'
    | '/app/'
    | '/docs/'
    | '/app/t/$id'
    | '/app/p/$chainId/$vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  SecurityRoute: typeof SecurityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/curator': {
      id: '/app/curator'
      path: '/curator'
      fullPath: '/app/curator'
      preLoaderRoute: typeof AppCuratorRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/trade': {
      id: '/app/trade'
      path: '/trade'
      fullPath: '/app/trade'
      preLoaderRoute: typeof AppTradeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/vault-agent': {
      id: '/docs/vault-agent'
      path: '/vault-agent'
      fullPath: '/docs/vault-agent'
      preLoaderRoute: typeof DocsVaultAgentRouteImport
      parentRoute: typeof DocsRoute
    }
    '/app/t/$id': {
      id: '/app/t/$id'
      path: '/t/$id'
      fullPath: '/app/t/$id'
      preLoaderRoute: typeof AppTIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/p/$chainId/$vault': {
      id: '/app/p/$chainId/$vault'
      path: '/p/$chainId/$vault'
      fullPath: '/app/p/$chainId/$vault'
      preLoaderRoute: typeof AppPChainIdVaultRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppCreateRoute: typeof AppCreateRoute
  AppCuratorRoute: typeof AppCuratorRoute
  AppMeRoute: typeof AppMeRoute
  AppTradeRoute: typeof AppTradeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTIdRoute: typeof AppTIdRoute
  AppPChainIdVaultRoute: typeof AppPChainIdVaultRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppCreateRoute: AppCreateRoute,
  AppCuratorRoute: AppCuratorRoute,
  AppMeRoute: AppMeRoute,
  AppTradeRoute: AppTradeRoute,
  AppIndexRoute: AppIndexRoute,
  AppTIdRoute: AppTIdRoute,
  AppPChainIdVaultRoute: AppPChainIdVaultRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DocsRouteChildren {
  DocsVaultAgentRoute: typeof DocsVaultAgentRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsVaultAgentRoute: DocsVaultAgentRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  SecurityRoute: SecurityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
