/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ListRouteImport } from './routes/list'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as DIdRouteImport } from './routes/d/$id'
import { Route as ESlugRouteImport } from './routes/e/$slug'
import { Route as LIdRouteImport } from './routes/l/$id'
import { Route as PDealRouteImport } from './routes/p/$deal'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MeProofDealRouteImport } from './routes/me/proof/$deal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const DIdRoute = DIdRouteImport.update({
  id: '/d/$id',
  path: '/d/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LIdRoute = LIdRouteImport.update({
  id: '/l/$id',
  path: '/l/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PDealRoute = PDealRouteImport.update({
  id: '/p/$deal',
  path: '/p/$deal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MeProofDealRoute = MeProofDealRouteImport.update({
  id: '/proof/$deal',
  path: '/proof/$deal',
  getParentRoute: () => MeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/import': typeof ImportRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/d/$id': typeof DIdRoute
  '/e/$slug': typeof ESlugRoute
  '/l/$id': typeof LIdRoute
  '/p/$deal': typeof PDealRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/me/proof/$deal': typeof MeProofDealRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/import': typeof ImportRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/d/$id': typeof DIdRoute
  '/e/$slug': typeof ESlugRoute
  '/l/$id': typeof LIdRoute
  '/p/$deal': typeof PDealRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/me/proof/$deal': typeof MeProofDealRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/import': typeof ImportRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/d/$id': typeof DIdRoute
  '/e/$slug': typeof ESlugRoute
  '/l/$id': typeof LIdRoute
  '/p/$deal': typeof PDealRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/me/proof/$deal': typeof MeProofDealRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/import'
    | '/list'
    | '/login'
    | '/me'
    | '/d/$id'
    | '/e/$slug'
    | '/l/$id'
    | '/p/$deal'
    | '/api/auth/$'
    | '/me/proof/$deal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/import'
    | '/list'
    | '/login'
    | '/me'
    | '/d/$id'
    | '/e/$slug'
    | '/l/$id'
    | '/p/$deal'
    | '/api/auth/$'
    | '/me/proof/$deal'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/import'
    | '/list'
    | '/login'
    | '/me'
    | '/d/$id'
    | '/e/$slug'
    | '/l/$id'
    | '/p/$deal'
    | '/api/auth/$'
    | '/me/proof/$deal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ImportRoute: typeof ImportRoute
  ListRoute: typeof ListRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRouteWithChildren
  DIdRoute: typeof DIdRoute
  ESlugRoute: typeof ESlugRoute
  LIdRoute: typeof LIdRoute
  PDealRoute: typeof PDealRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$id': {
      id: '/d/$id'
      path: '/d/$id'
      fullPath: '/d/$id'
      preLoaderRoute: typeof DIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$id': {
      id: '/l/$id'
      path: '/l/$id'
      fullPath: '/l/$id'
      preLoaderRoute: typeof LIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$deal': {
      id: '/p/$deal'
      path: '/p/$deal'
      fullPath: '/p/$deal'
      preLoaderRoute: typeof PDealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/proof/$deal': {
      id: '/me/proof/$deal'
      path: '/proof/$deal'
      fullPath: '/me/proof/$deal'
      preLoaderRoute: typeof MeProofDealRouteImport
      parentRoute: typeof MeRoute
    }
  }
}

interface MeRouteChildren {
  MeProofDealRoute: typeof MeProofDealRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeProofDealRoute: MeProofDealRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ImportRoute: ImportRoute,
  ListRoute: ListRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRouteWithChildren,
  DIdRoute: DIdRoute,
  ESlugRoute: ESlugRoute,
  LIdRoute: LIdRoute,
  PDealRoute: PDealRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
